# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IrisCalendarApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FSCalendar'
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxAlamofire'

  # Pods for IrisCalendarApp

  target 'IrisCalendarAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IrisCalendarAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
